workflows:
  android-apk:
    name: Build Android APK
    environment:
      vars:
        GRADLE_TASK: "assembleDebug" # Use "assembleRelease" for a release build
        JAVA_VERSION: 11 # Specify Java version
    triggering:
      events:
        - push # Triggers the workflow on push
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing Gradle dependencies..."
          chmod +x gradlew
          ./gradlew dependencies
      - name: Build the APK
        script: |
          echo "Building APK..."
          ./gradlew $GRADLE_TASK
      - name: Export APK
        script: |
          echo "Exporting APK..."
          mkdir -p $CM_BUILD_DIR/artifacts/apk
          cp app/build/outputs/apk/debug/*.apk $CM_BUILD_DIR/artifacts/apk/ # Update path if necessary
    artifacts:
      - $CM_BUILD_DIR/artifacts/apk/*.apk # Exports the built APK
